export { RootMail } from "./client";
export type { RootMailOptions, RequestOptions } from "./client";
export { RootMailError } from "./errors";
export { Messages } from "./resources/messages";
export { SubTenants } from "./resources/sub-tenants";
export { Contacts } from "./resources/contacts";
export { Templates } from "./resources/templates";
export { Sequences } from "./resources/sequences";
export { Lists } from "./resources/lists";
export { Campaigns } from "./resources/campaigns";
export { Threads } from "./resources/threads";
export { Webhooks } from "./resources/webhooks";
export { DeliverabilityResource, AnalyticsResource } from "./resources/insights";
export { Exports, Retention } from "./resources/compliance";
export { Imports } from "./resources/imports";
export { Assistant } from "./resources/assistant";
export * from "./types";
